{% set name = "twine" %}
{% set version = "6.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e5ed0d2fd70c9959770dce51c8f39c8945c574e18173a7b81802dab51b4b75cf

build:
  skip: true  # [py<39]
  entry_points:
    - twine = twine.__main__:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools >=77.0.3
    - setuptools_scm >=6.0
  run:
    - python
    - readme_renderer >=35.0
    - requests >=2.20
    - requests-toolbelt !=0.9.0,>=0.8.0
    - urllib3 >=1.26.0
    - importlib-metadata >=3.6  # [py<310]
    - keyring >=21.2.0
    - rfc3986 >=1.4.0
    - rich >=12.0.0
    - packaging >=24.0
    - id
  # run_constrained:
  #   - keyring >=21.2.0          # [s390x]

test:
  requires:
    - pip
    - pretend
    - pytest
  source_files:
    - twine
    - tests
  imports:
    - twine
    - twine.commands
  commands:
    - pip check
    - pytest -v tests --ignore-glob '*integration*.py' --ignore=tests/test_check.py  
    # Upstream is still figuring out how to handle keyring on s390x.# [not s390x]
    # https://github.com/pypa/twine/issues/1158
    # - pytest -v tests --ignore-glob '*integration*.py' --ignore=tests/test_check.py -k "not (keyring or test_values_from_env or test_no_color_exception or test_http_exception_handling or test_exception_handling or test_catches_enoent or test_dispatch_to_subcommand or test_warns_for_empty_password)"  # [s390x]

about:
  home: https://github.com/pypa/twine
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Collection of utilities for interacting with PyPI
  description: |
    Twine is a utility for publishing Python packages on PyPI.
    It provides build system independent uploads of source and 
    binary distribution artifacts for both new and existing projects.
  dev_url: https://github.com/pypa/twine
  doc_url: https://twine.readthedocs.io

extra:
  recipe-maintainers:
    - SylvainCorlay
    - bollwyvl
