{% set name = "twine" %}
{% set version = "4.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/twine-{{ version }}.tar.gz
  sha256: 9e102ef5fdd5a20661eb88fad46338806c3bd32cf1db729603fe3697b1bc83c8

build:
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  number: 0

requirements:
  host:
    - python
    - setuptools >=45
    - wheel
    - setuptools_scm >=6.0
    - pip
  run:
    - python
    - pkginfo >=1.8.1
    - readme_renderer >=35.0
    - requests >=2.20
    - requests-toolbelt !=0.9.0,>=0.8.0
    - urllib3 >=1.26.0
    - importlib-metadata >=3.6
    - keyring >=15.1
    - rfc3986 >=1.4.0
    - rich >=12.0.0

test:
  imports:
    - twine
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pypa/twine
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Collection of utilities for interacting with PyPI
  description: |
    Twine is a utility for publishing Python packages on PyPI.
    It provides build system independent uploads of source and 
    binary distribution artifacts for both new and existing projects.
  dev_url: https://github.com/pypa/twine
  doc_url: https://twine.readthedocs.io

extra:
  recipe-maintainers:
    - SylvainCorlay
    - bollwyvl
