{% set version = "3.7.1" %}

package:
  name: twine
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/twine/twine-{{ version }}.tar.gz
  sha256: 28460a3db6b4532bde6a5db6755cf2dce6c5020bada8a641bb2c5c7a9b1f35b8

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<36]
  entry_points:
    - twine = twine.__main__:main

requirements:
  host:
    - pip
    - python
    - setuptools >=0.7.0
    - setuptools_scm >=1.15
  run:
    - colorama >=0.4.3
    - importlib_metadata >=3.6
    - keyring >=15.1
    - pkginfo >=1.4.2
    - python
    - readme_renderer >=21.0
    - requests >=2.20
    - requests-toolbelt >=0.8.0,!=0.9.0
    - rfc3986 >=1.4.0
    - setuptools >=0.7.0
    - tqdm >=4.14

test:
  requires:
    - pip
  imports:
    - twine
    - twine.commands
  commands:
    - python -m pip check
    - twine --version
    - twine --help

about:
  home: https://github.com/pypa/twine
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Collection of utilities for interacting with PyPI
  doc_url: https://twine.readthedocs.io
  doc_source_url: https://github.com/pypa/twine/tree/master/docs

extra:
  recipe-maintainers:
    - SylvainCorlay
    - bollwyvl
