travis:
  secure:
    BINSTAR_TOKEN: myLC7VA/OjJg5PVPl10/SHWliKJcYbRO1TOQtT9S8h7hBI235DcLrxruCPjQiR3yVCI8RX8gCkE0uXRK7Bh38zL3KlqbrtEizuiY3N7r6ZvQQJtMqlHKky+9sN1bstHJRN0DDNMyjryRjNm5fAKdDeO/k9GjjSu7m+sgc4g8SfuLLUAcHuQ3unbObsodrqbmObgrgA916BDdV/CIeJ6c86nfaTTtvM32mA68Bj5a7ezSjaA/mvakzUxlnBbq7m2lLGTiKmmWe/xw8UEjEH0lxFGZFwHFj2XKoG41eFq3VK8ZKa7Hco2x9aS9wGyvUqGjXOHIoeVobbSI7lWS1EF37RUf6c4WYZ10hTOyKPGQ6a0QBnky6lhlS/EL/nMMOMIZDt4PyEPLPc+9LT/rTziBaEJGnhIc2PvfR0tSFRYlT9TI2nOkKAf8KQguO+6tEfymvu+tXeit0do7TqGQ2bJpAt7egigoG8ub18giSkL2+B2bF2Wcm3Vwhk0lF0I+g43eXiP4YIDMOi94zixs9S5aPlOSdDfcEo+xVeTn0BwYKoMpmhx2bzas3NVEpD7z4okVj2UdAFls2HeZkbfjmk6qtX6ApSqby+vizecuuV9yEF6XHp74dvBiTW4C6MNmRy4p53UH8uzHuCPYm6ZQXcvjw5v05nl5mqJUjKLixekdSaM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
