travis:
  secure:
    BINSTAR_TOKEN: nRVOQSA80gy3vn2MBsdcRzOoVkz0VFWcAiFGx9cpcku/7l7hO4FsgG/txvKlkJTCAoWwjj01VNBXZgFwy/5wZRjalGYVWq2W/BOuWauKj1Xc/t+ptGkD8TKPz9FTi1D3Vt56GYFggDfmcparBMyB46r2tGB2hVrlHjsLhxtOYa0G0z0SMwgTyBpe5wK1S7ur5M15GVTEfqK7cASPDpYCcST6GDqZ2JtopAbdZ/wTT2ANv10HSQo1sDZ2UQxcwNMI+88+DJjO2InDctFnKoSlKJFAjZdK6s+meaLpXa7bOdn5ALCbYyIiGN7ydX1DoBh4a5LqfQEvq4jfdIDQOsCiWj9QmwMalnzQGIa43JlJqKApa86oYYhyFC/pG1c13DX5SPgDFlsZg750KIPUurpvBLCTtDrN45NIaDwqzFP7T/Mwdxi3IanG/2+pDcjpr+aT3HBZ6ISy/sfMfVSf1wmNHw2o1TOopKNqjDOAYymwSW1hFzHXCMXt//qiuyKe7FhlcY44Qm3jsD5X5xKAPc1o6p8Hr1FcYQAiHXo0B3JZWF0Pn8jEsqAv6duIfHWSuRExSmRaS7ySQeVE+fC9rTHt1VUxrQUj7omaHJNdjKYBADA2p+ZnMUWeDaA2kHUlQNf6u28Rnfj/7UmcJJpDYDbvT/7KF0EpmXmpUUCa5GbIToY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
